# Generated by Django 2.0.5 on 2018-11-26 08:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_auto_20181123_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 26, 8, 45, 43, 699197, tzinfo=utc)),
        ),
    ]
